name: hook
on:
  push:
    branches: [ "huve" ]
  pull_request:
    branches: [ "huve" ]

jobs:
  hook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 1

      - name: install test deps
        run: sudo apt-get install shfmt shellcheck

      - name: execute hooking script
        run: ./poli.sh VERBOSE
