name: hook
on:
  push:
    branches: [ "huve" ]
  pull_request:

jobs:
  hook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 1

      - name: setup git
        run: |
          git config --global user.email "runner@example.com"
          git config --global user.name "Github Runner"
          git --version

      - name: install test deps
        run: |
          sudo printf "%s\n" "set man-db/auto-update false" | sudo debconf-communicate
          sudo rm /var/lib/man-db/auto-update
          sudo apt-get install shfmt shellcheck

      - name: get ubuntu env
        run: |
          echo ***SHFMT***
          shfmt --version
          echo ***SHELLCHECK***
          shellcheck --version

      - name: execute hooking script
        run: ./poli.sh VERBOSE
