name: ci-hook
on:
  push:
    branches: [ "huve" ]
  pull_request:
    branches: [ "huve" ]

jobs:
  hook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: do the hook
        run: |
          sudo apt-get install shfmt shellcheck
          ./hook.sh SILENT
